### ISSUE TITLE
Add semgrep and caracal to CI

### ISSUE THREAD

**Issue by rcatalan98** [lambdaclass/yet-another-swap#101]
You can check how it's implemented in [Satoru](https://github.com/keep-starknet-strange/satoru/blob/main/.github/workflows/security.yml)

**Comment by dbejarano820** [comment]
I can add this

**Comment by rcatalan98** [comment]
> I can add this

Thanks Beja! I'll DM you in Telegram so we can set up a quick call to talk about this.
