### ISSUE TITLE
Add deployment script

### ISSUE THREAD

**Issue by rcatalan98** [lambdaclass/yet-another-swap#112]
Right now we are using only `starkli` to declare and deploy our contracts, this is fine for now but for more testing and a production ready project we will need a deployment script. Main reason being there are a lot of areas to make mistakes but just using the CLI and the Makefiles.

The script should be done in Rust and using [starknet-rs](https://github.com/xJonathanLEI/starknet-rs).

**Comment by ftupas** [comment]
Hello, may I take this one?
