### ISSUE TITLE
Add format pre-commit

### ISSUE THREAD

**Issue by rcatalan98** [lambdaclass/yet-another-swap#125]
Include `scarb fmt` and `npx prettier --check ` in the pre-commit.

**Comment by pfcrowe** [comment]
can i take this?

**Comment by rcatalan98** [comment]
> can i take this?

Hey thanks for taking us into consideration. Yes you can take it! To do this properly we will create a new repository in Github that will be used only for the pre-commit. This will allowed other projects to use it in the future.
