### ISSUE TITLE
Add version specification of scarb at README

### ISSUE THREAD

**Issue by sm-stack** [lambdaclass/yet-another-swap#151]
Scarb version `2.3.0` uses Cairo `2.3.0`, and openzeppelin cairo contract is not currently fully compatible with that version of Cairo. So if someone tries `make build` with scarb `2.3.0`, he will get an error.

We can track their progress to migrate to Cairo 2.3.0 at [this issue](https://github.com/OpenZeppelin/cairo-contracts/issues/751) and [the roadmap](https://github.com/orgs/OpenZeppelin/projects/29/views/1).

So, specifying scarb version that is compatible with openzeppelin contracts will help people start more easily, before openzeppelin starts to support Cairo `2.3.0`. Optimal version is now scarb `0.7.0` & cairo `2.2.0`.

**Comment by 0xjunger** [comment]
If I have the latest version of Scarb(2.3.0), what is the way to use older version(0.7.0)?

**Comment by sm-stack** [comment]
> If I have the latest version of Scarb(2.3.0), what is the way to use older version(0.7.0)?

Using asdf can be one of the solutions, I think.
