### ISSUE TITLE
Add Error Handling for Libraries

### ISSUE THREAD

**Issue by rcatalan98** [lambdaclass/yet-another-swap#23]
We should avoid `panics` in the libraries and use a proper error handling mechanism. There needs to be some research done to see what's the current standard for Cairo libraries.
[Check out this examples from the Cairo Book](https://book.cairo-lang.org/ch10-00-error-handling.html).

This are the files we should refactor:
- [bit_math.cairo](https://github.com/lambdaclass/yet-another-swap/blob/main/crates/yas_core/src/libraries/bit_math.cairo)
- [liquidity_math.cairo](https://github.com/lambdaclass/yet-another-swap/blob/main/crates/yas_core/src/libraries/liquidity_math.cairo)
- [sqrt_price_math.cairo](https://github.com/lambdaclass/yet-another-swap/blob/main/crates/yas_core/src/libraries/sqrt_price_math.cairo)
- [tick_math.cairo](https://github.com/lambdaclass/yet-another-swap/blob/main/crates/yas_core/src/libraries/tick_math.cairo)

The refactor consists on:
- Making the functions of those libraries that use assert return `Result` instead.
- Refactoring the other libraries or contracts that use the lower libraries. This is where the errors with pattern matching should be handled.
- Refactoring the tests to try the errors.

This is an [example](https://github.com/lambdaclass/yet-another-swap/blob/main/src/contracts/yas_pool.cairo#L767-L778) of how errors from lower libraries should be handled.

**Comment by faytey** [comment]
Hi @rcatalan98 can i take up this task

**Comment by rcatalan98** [comment]
> Hi @rcatalan98 can i take up this task

Hey! Sure you can! Let us know if you need more clarity on the task. Thanks for contributing

**Comment by faytey** [comment]
Yes please, can you share more information on the task please

**Comment by rcatalan98** [comment]
> Yes please, can you share more information on the task please

Hey, we just merged some code with a great example to understand what we mean.

The idea is to do a refactor and avoid doing asserts at the library level, leaving that responsibility to the contract using it.

[Here](https://github.com/lambdaclass/yet-another-swap/blob/main/src/contracts/yas_pool.cairo#L767-L778) is an example of what we would like. We return a `Result` and the function with important logic in the contract decides to panic.

Does it make sense?

**Comment by faytey** [comment]
Yes it does, thanks for the explanation, hopping on it right away

**Comment by faytey** [comment]
Hi @rcatalan98 I left you a mail some days ago but didn't get a response. I was able to get some help and made some progress, I need you to see if what i'm doing is what's needed, here's my version of the contribution working on the forked repo, I'd create a pr when it's okay https://github.com/faytey/yet-another-swap/tree/error_handling

**Comment by rcatalan98** [comment]
> Hi @rcatalan98 I left you a mail some days ago but didn't get a response. I was able to get some help and made some progress, I need you to see if what i'm doing is what's needed, here's my version of the contribution working on the forked repo, I'd create a pr when it's okay https://github.com/faytey/yet-another-swap/tree/error_handling

Hi @faytey please always use this comment section for communication. Emails might get lost with other things. Or you can also send us a message in telegram.

Can you make a PR as draft so it's easier to review the work you have done so far?

**Comment by faytey** [comment]
Alright, doing that now

**Comment by faytey** [comment]
I've made a pull request, thanks

**Comment by faytey** [comment]
Hello @rcatalan98  i'm awaiting your feedback

**Comment by faytey** [comment]
Hello, I still await your response please
