### ISSUE TITLE
Add Tick library

### ISSUE THREAD

**Issue by rcatalan98** [lambdaclass/yet-another-swap#8]
Check the official[ library from Uniswap V3](https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/Tick.sol).

Tracking issue:
- [x] #47 
- [x] #48 
- [x] #49 
- [x] #50 
- [x] #51 
- [x] #53

**Comment by h3lio5** [comment]
can I take this ser?

**Comment by rcatalan98** [comment]
Hey! This issue was actually divided in multiple issues per function and all of them are taken at the moment. We forgot to make this clear. Where we need help is with #61 if you want to start somewhere. I'll be adding other issues too this week.
Thanks for being open to collaborate!

**Comment by rcatalan98** [comment]
> can I take this ser?
Hey! This issue was actually divided in multiple issues per function and all of them are taken at the moment. We forgot to make this clear. Where we need help is with https://github.com/lambdaclass/yet-another-swap/issues/61 if you want to start somewhere. I'll be adding other issues too this week.
Thanks for being open to collaborate!
