### ISSUE TITLE
Add #[key] tag to YASFactory contract 

### ISSUE THREAD

**Issue by dubzn** [lambdaclass/yet-another-swap#80]
The `#[key]` tags were not added to the events of the YASFactory contract because when comparing the values in the tests, we encountered values that did not match our expectations. The issue would involve adding the `#[key] `tags (as needed) to the `OwnerChanged`, `PoolCreated`, `FeeAmountEnabled` events, understanding the process, and adapting the tests.

Some questions:
- How are the values of the event attributes displayed when they have the #[key] tag?
- Would the values lose their original meaning if we use them as keys?

Sources:
[Contract Events ](https://book.cairo-lang.org/ch99-01-03-03-contract-events.html#defining-events)

**Comment by codeWhizperer** [comment]
I would like to work on this. And using an attribute as a key doesn't necessarily change the original meaning of its value. I think the original meaning will be retained.

Kindly assign me this issue

**Comment by WiseMrMusa** [comment]
I guess you can just work on it and create a PR

**Comment by rcatalan98** [comment]
> I would like to work on this. And using an attribute as a key doesn't necessarily change the original meaning of its value. I think the original meaning will be retained.
> 
> Kindly assign me this issue

Hey thanks for taking us into consideration! You don't need the issue to be assigned to you to start working on this.
To contribute you will have to fork the project and then do a PR to YAS. I highly recommend creating one branch per PR you make to avoid conflicts in your main branch.

What we for this issue is not only to do the refactor but also provide a reasoning on what's the best way to structure the Event.

**Comment by codeWhizperer** [comment]
Awesome. I will get started with it.

**Comment by codeWhizperer** [comment]
@rcatalan98 I have an update on this.

I found out that the reason why the tests are failing is beacause: 
 the keys in events always contain the event name hash key as first key, but this is not part of the event enum, so the deserialziation is "shifted right" when using pop_log.

Fix to the issue: 

This should be handled in the pop_log function at some point, but in the meantime you can add a wrapper, and remove the first key, and everything will work as expected.

Here's a reference to the fix from Oz:

https://github.com/OpenZeppelin/cairo-contracts/blob/258daba0f4e85fcc8bc1f142ce1b2bdf328453b3/src/tests/utils.cairo#L24

I replaced the pop_log from starknet and replaced it with the the pop_log with the wrapper from OZ and the tests passes successfully when #[key] are added to index event. BUt without adding the #[key] attributes the tests fail.


I am still looking into how to make the test pass for both cases


Just wanted to drop the update

**Comment by rcatalan98** [comment]
Closed in #110
