### ISSUE TITLE
Add Proxy contract

### ISSUE THREAD

**Issue by rcatalan98** [lambdaclass/yet-another-swap#95]
Implement a Proxy contract to allow upgradable contracts for YAS.

**Comment by 0xKermo** [comment]
which contract will be upgradable, i think pool contract should not be upgradable

**Comment by rcatalan98** [comment]
> which contract will be upgradable, i think pool contract should not be upgradable

Factory and Router. I agree with you. Do you have any suggestions regarding this?

**Comment by 0xKermo** [comment]
In Uniswap V3, only the Router contract is a proxy, not the Factory contract. I think this is to guarantee that the created pools are the same.
